"""add password in user

Revision ID: 796b65ad3728
Revises: 15129032e797
Create Date: 2025-03-30 13:10:29.918720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '796b65ad3728'
down_revision = '15129032e797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('_password_hash')

    # ### end Alembic commands ###
